<a href="https://colab.research.google.com/github/5r33kanth/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [4]:
#please provide your answer below this line.
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.03554117 0.25204297 0.03956111]
  [0.33087924 0.67119045 0.17488418]
  [0.49918801 0.95875698 0.28376045]]

 [[0.23722878 0.6176292  0.39740532]
  [0.64247744 0.93229841 0.97419214]
  [0.2736509  0.3940584  0.74480365]]

 [[0.94634088 0.78954463 0.07674853]
  [0.65561142 0.54339979 0.89546208]
  [0.21772511 0.0864645  0.07840734]]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [45]:
#please provide your answer below this line.
import numpy as np
s=np.full((4,4),3)
r=s.reshape(2,8) 
e=np.full((4,4),1)
k=e.reshape(2,8)
a=np.stack((r,k),axis=1 )
print(a)
n=np.hstack((r,k))
print(n)


[[[3 3 3 3 3 3 3 3]
  [1 1 1 1 1 1 1 1]]

 [[3 3 3 3 3 3 3 3]
  [1 1 1 1 1 1 1 1]]]
[[3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1]]
