<a href="https://colab.research.google.com/github/5r33kanth/LEARN.PY/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np
a = np.random.rand(3,3)
b = np.random.rand(3,3)
print(a)
print(b)
x=np.dot(a,b)
print(x)
x.transpose()


[[0.761086   0.64139832 0.8531467 ]
 [0.16329616 0.02834339 0.19983247]
 [0.91725423 0.0230715  0.63414938]]
[[0.34950517 0.9579     0.72117449]
 [0.71357098 0.1727548  0.5920515 ]
 [0.73898828 0.2887876  0.77484364]]
[[1.35415212 1.08622711 1.58967194]
 [0.22497173 0.21902699 0.28938469]
 [0.80567721 1.06575802 1.16652649]]


array([[1.35415212, 0.22497173, 0.80567721],
       [1.08622711, 0.21902699, 1.06575802],
       [1.58967194, 0.28938469, 1.16652649]])

2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.
import numpy as np
a=[[55,25,15], [30,44,2], [11,45,77]]
b=np.array(a)
print(b)
np.linalg.det(b)

[[55 25 15]
 [30 44  2]
 [11 45 77]]


137180.0000000001