<a href="https://colab.research.google.com/github/5r33kanth/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [2]:
#please provide your answer below this line.
import numpy as np
x = np.random.rand(3,3)
print(x)

[[0.74549707 0.34793391 0.94777639]
 [0.30366642 0.33472261 0.49509714]
 [0.3785128  0.60422495 0.6679469 ]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [16]:
#please provide your answer below this line.
import numpy as np
a=np.arange(0,16).reshape(4,4)
b=np.arange(6,22).reshape(4,4)
x=np.vstack(a).reshape(8,2)
y=np.hstack(b).reshape(2,8)
print(x)
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
