<a href="https://colab.research.google.com/github/5r33kanth/LEARN.PY/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [6]:
#please provide your answer below this line.
import numpy as np
x = np.random.rand(3,3)
y = np.random.rand(3,3)

print(x)
print(y)

a=np.dot(x,y)
print(a)
a.transpose()

[[0.10869407 0.97384329 0.32369723]
 [0.7469113  0.38878482 0.86693452]
 [0.10625029 0.27462512 0.7908248 ]]
[[0.36434026 0.73318723 0.03408721]
 [0.88568555 0.74079498 0.8709467 ]
 [0.55792041 0.01218453 0.5666404 ]]
[[1.08271784 0.80505542 1.0352906 ]
 [1.10015141 0.84619886 0.8553111 ]
 [0.72316005 0.29097809 0.69091889]]


array([[1.08271784, 1.10015141, 0.72316005],
       [0.80505542, 0.84619886, 0.29097809],
       [1.0352906 , 0.8553111 , 0.69091889]])

2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [11]:
#please provide your answer below this line.
import numpy as np
a=[[55,25,15], [30,44,2], [11,45,77]]
b=np.array(a)
print(b)
np.linalg.det(b)


[[55 25 15]
 [30 44  2]
 [11 45 77]]


137180.0000000001